version: '3.8'

services:
  dorky:
    build: .
    container_name: dorky
    volumes:
      - .:/app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"